services:
  newsflash-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsflash-api  # Nome do container definido
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-newsflash:27017/newsflash
    depends_on:
      - mongodb-newsflash
    networks:
      - newsflash-network

  mongodb-newsflash:
    image: mongo:5.0
    container_name: mongodb-newsflash
    ports:
      - "27018:27017"  # Porta diferente para evitar conflitos
    networks:
      - newsflash-network
    volumes:
      - mongodb_newsflash_data:/data/db

  redis-newsflash:
    image: redis:7
    container_name: redis-newsflash
    ports:
      - "6380:6379"  # Porta diferente para evitar conflitos
    volumes:
      - redis_newsflash_data:/data
    networks:
      - newsflash-network

networks:
  newsflash-network:
    driver: bridge

volumes:
  mongodb_newsflash_data:
  redis_newsflash_data: