version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - newsflash-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - newsflash-network

networks:
  newsflash-network:
    driver: bridge

volumes:
  mongodb_data: